# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-19 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170502_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='twitter_user',
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
    ]
